### ISSUE TITLE
State does not provide correct selected filter for output

### ISSUE THREAD

**Issue by Andrewwf1** [Arnnav-A/207-Project#18]
**Describe the bug**
"Apply" button got wrong state: the State does NOT match the selection for the first parent filter. By debugger, it shows that the selection of the first filter didn't update in the state so that "Apply" got "empty" selection. Try "apply" filter with only the first filter, first & second filter to see difference. [It work now because I changed it from state.getSelectedParentFilter() to getFilterViewModel.getParentFilter(), which means directly asking viewModel for this data, Nov 20]

One guess for this bug is because I modified the parent filter to be a String, rather than a String[]. Since the rest 3 filters have no problem and they are String[], so I think this might cause some disconnection of update between files.

**To Reproduce**
1. Go to 'Main' and run.
2. Click on 'Get Filters' on the panel
3. Choose only one of the first line filters
4. Click on 'Apply'
5. See error

**Expected behavior**
It should return selected filter when click on 'Apply'. It will be auto-filled to Filter input space without poping up an error notification.

**Comment by Andrewwf1** [comment]
Now it has been fixed. 
All filter selection can be returned in right format and right value.

**Comment by Arnnav-A** [comment]
Fixed by PR#10
