### ISSUE TITLE
Too little information given from get_history use case

### ISSUE THREAD

**Issue by JG808** [Arnnav-A/207-Project#22]
**Is your feature request related to a problem? Please describe.**
When getting user history, there are only information about the searched city name and filter name. This information is not helpful enough to be considered as an important feature.

**Describe the solution you'd like**
We can create a link or button so that once the user clicks a user history, they can get the information from that search. Specifically, go back to the ViewModel of the search.

**Describe alternatives you've considered**
Alternatively, we can get a shortcut of what the search result is(e.g., Time, Toronto, Food, {LCBO; McDonald's; The Beer Store}

**Comment by Arnnav-A** [comment]
Considered not important anymore
